global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
      api_version: v1

rule_files: []

scrape_configs:
  - job_name: 'parallax-pal-backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['backend:8000']
    scheme: http

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Docker metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['docker.for.mac.localhost:9323']  # For Mac
      # - targets: ['docker.for.win.localhost:9323']  # For Windows
    metrics_path: '/metrics'

  # System metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 5s

  # Application-specific metrics
  - job_name: 'parallax-pal-metrics'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['backend:8000']
    scheme: http
    scrape_interval: 10s
    scrape_timeout: 5s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '(.*)'
        replacement: '$1'
      - source_labels: [__metrics_path__]
        target_label: metrics_path
        regex: '(.*)'
        replacement: '$1'